import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync('js/chart-tags.js','utf8');
const ctx=vm.createContext({clearTimeout,setTimeout});
vm.runInContext(source.replaceAll('export ',''),ctx);
const normalize=values=>Array.from(ctx.normalizeTags(values));
assert.deepEqual(normalize([' 高難度 ','多押','技術譜','高難度']),['高難度','多押','技術譜']);
assert.deepEqual(normalize([' Tech ','tech','TECH']),['tech']);
assert.deepEqual(normalize([]),[]);
assert.throws(()=>normalize(['  ']));
assert.throws(()=>normalize([null]));
assert.throws(()=>normalize(['字'.repeat(21)]));
assert.equal(normalize(['😀'.repeat(20)])[0].length,40);
assert.throws(()=>normalize(Array.from({length:11},(_,i)=>`tag${i}`)));
assert.equal(normalize(Array.from({length:10},(_,i)=>`tag${i}`)).length,10);
const elements=()=>({children:[],value:'',disabled:false,replaceChildren(){this.children=[];},append(item){this.children.push(item);},setAttribute(){},addEventListener(type,fn){this[type]=fn;}});
ctx.document={createElement:elements};
const container=elements(),input=elements(),button=elements(),hint=elements();
const editor=ctx.createTagEditor(container,input,button,hint);
input.value='高難度';input.keydown({key:'Enter',isComposing:false,preventDefault(){}});
input.value='高難度';button.onclick();assert.equal(editor.get().length,1);
input.value='<script>';button.onclick();assert.equal(container.children[1].textContent,'<script> ×');
container.children[0].onclick();assert.deepEqual(Array.from(editor.get()),['<script>']);
editor.set(Array.from({length:10},(_,i)=>`tag${i}`));assert.equal(button.disabled,true);
input.value='extra';button.onclick();assert.equal(editor.get().length,10);assert.match(hint.textContent,/10/);
editor.set([]);assert.equal(button.disabled,false);
const calls=[];
const apiContext=vm.createContext({normalizeTags:ctx.normalizeTags,currentUser:{id:'a'},supabase:{rpc:async(name,args)=>{calls.push({name,args});return {data:[]};}}});
vm.runInContext(fs.readFileSync('js/api.js','utf8').replace(/^import .*;\r?\n/gm,'').replaceAll('export ',''),apiContext);
await apiContext.setChartTags('a',['高難度','Tech','TECH']);
assert.equal(calls[0].name,'set_chart_tags');assert.deepEqual(Array.from(calls[0].args.tag_names),['高難度','tech']);
await assert.rejects(()=>apiContext.setChartTags('a',['x'.repeat(21)]));assert.equal(calls.length,1);
await apiContext.setChartTags('a',[]);assert.equal(calls[1].args.tag_names.length,0);
await apiContext.searchCharts();
assert.equal(calls[2].name,'search_charts');
assert.deepEqual(JSON.parse(JSON.stringify(calls[2].args)),{query:'',tag_filter:null,diff:null,min_r:1,max_r:null,we_star_filter:null,we_attribute_filter:null,sort_by:'published_at',page_limit:20,page_offset:0});
await apiContext.searchCharts({query:'高難度',tagId:7,difficulty:'EXPERT',minRating:12,maxRating:14,sortBy:'rating_desc',page:2,limit:5});
assert.deepEqual(JSON.parse(JSON.stringify(calls[3].args)),{query:'高難度',tag_filter:7,diff:'EXPERT',min_r:12,max_r:14,we_star_filter:null,we_attribute_filter:null,sort_by:'rating_desc',page_limit:5,page_offset:10});
const sql=fs.readFileSync('supabase/migrations/20261006_custom_chart_tags.sql','utf8');
assert.match(sql,/owner_id IS DISTINCT FROM auth.uid\(\)/);assert.match(sql,/FOR UPDATE/);
assert.match(sql,/cardinality\(names\)>10/);assert.match(sql,/ON CONFLICT DO NOTHING/);
assert.match(sql,/REVOKE INSERT,UPDATE,DELETE/);assert.match(sql,/SECURITY INVOKER/);
assert.ok(!sql.includes('DROP TABLE'));assert.ok(!sql.includes('UPDATE public.charts'));
assert.ok(!sql.includes('storage.objects'));assert.ok(!sql.includes('CREATE TABLE public.charts'));
assert.equal((sql.match(/^COMMIT;/gm)||[]).length,1);
assert.ok(!/CREATE\s+TEMP/i.test(sql));
assert.equal((sql.match(/WITH tag_canonical_map AS/g)||[]).length,5);
assert.match(sql,/NOTIFY pgrst, 'reload schema'/);
const searchSQL=sql.slice(sql.indexOf('CREATE FUNCTION public.search_charts('));
assert.match(searchSQL,/tag_filter INTEGER DEFAULT NULL/);
assert.match(searchSQL,/c.status = 'published'/);
assert.match(searchSQL,/c.rating BETWEEN min_r AND max_r/);
assert.match(searchSQL,/diff IS NULL OR c.difficulty = diff/);
assert.match(searchSQL,/tag_filter IS NULL OR EXISTS/);
assert.match(searchSQL,/t.name ILIKE/);
assert.match(searchSQL,/LIMIT page_limit OFFSET page_offset/);
assert.match(searchSQL,/TO anon,authenticated/);
for(const path of ['js/api.js','js/pages/chart-detail.js'])assert.ok(!fs.readFileSync(path,'utf8').includes('chart_tag_votes'));
console.log('PASS: tag normalization, duplicates, Unicode length, limits, Enter/add/remove editor, text-safe chips, API validation/atomic RPC and migration security structure. Database execution not tested.');
