import fs from 'node:fs';
import assert from 'node:assert/strict';
const sql = fs.readFileSync(new URL('../supabase/initialize-backend.sql',import.meta.url),'utf8');
const api = fs.readFileSync(new URL('../js/api.js',import.meta.url),'utf8');
const auth = fs.readFileSync(new URL('../js/auth.js',import.meta.url),'utf8');
const storage = fs.readFileSync(new URL('../js/storage.js',import.meta.url),'utf8');
const tables = new Set([...sql.matchAll(/CREATE TABLE public\.(\w+)/g)].map(m=>m[1]));
for (const match of (api+auth+storage).matchAll(/supabase\s*\.from\('([^']+)'\)/g)) assert.ok(tables.has(match[1]),`Missing table ${match[1]}`);
for (const match of storage.matchAll(/\.storage\s*\.from\('([^']+)'\)/g)) assert.ok(sql.includes(`('${match[1]}',`),`Missing bucket ${match[1]}`);
assert.equal(tables.size,10);
assert.equal([...sql.matchAll(/\$\$/g)].length % 2,0);
assert.ok(!/AS \$(?!\$)/.test(sql),'broken function dollar quoting');
assert.ok(!/\b(DROP|TRUNCATE|DELETE FROM)\b/i.test(sql.replace(/--[^\n]*/g,'')));
assert.ok(/user_id\s+UUID\s+NOT NULL REFERENCES auth.users\(id\)/.test(sql));
assert.ok(sql.includes('REFERENCES public.profiles(id)'));
assert.ok(sql.includes('WITH CHECK (auth.uid() = user_id)'));
assert.ok(sql.includes('ON CONFLICT (id) DO NOTHING'));
assert.ok(sql.includes('strip_path TEXT, package_path TEXT'));
assert.ok(sql.includes('GRANT USAGE ON SEQUENCE public.downloads_id_seq'));
assert.ok(!sql.includes('reviews_id_seq'));
for (const table of tables) assert.ok(sql.includes(`ALTER TABLE public.${table} ENABLE ROW LEVEL SECURITY`),table);
for (const action of ['select','insert_own','update_own','delete_own']) assert.ok(sql.includes(`CREATE POLICY studio_storage_${action}`));
for (const rpc of ['search_charts','increment_view']) assert.ok(sql.includes(`CREATE FUNCTION public.${rpc}`));
console.log('PASS: static initialization SQL / frontend API table and bucket parity, RLS declarations, transaction artifacts, RPC paths, UUID FK, grants and non-destructive statements. SQL execution not tested.');
